server:
  port: 8083
  servlet:
    session:
      timeout: 1800
      tracking-modes: cookie

file:
  dir: C:/jth/works/mall/src/main/resources/static/assets/

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: mall
    password: mall
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
#      create,update,validate,none
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

  servlet:
    multipart:
      enabled: true
      max-file-size: 250MB
      max-request-size: 500MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace