server:
  port: 8083
  servlet:
    session:
      timeout: 1800
      tracking-modes: cookie

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: mall
    password: mall
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug